const odv_pro_id_details = [
  {
    field: "s1",
    headerName: "Seq",
    align: "center",
    sortable: false,
    width: 60,
  },
  {
    field: "marchio",
    headerName: "Marchio",
    sortable: false,
    editable: true,
    width: 120,
  },
  {
    field: "linea",
    headerName: "Linea",
    sortable: false,
    editable: true,
    width: 130,
  },
  {
    field: "codice",
    headerName: "Codice",
    sortable: false,
    editable: true,
    width: 120,
  },
  {
    field: "dex",
    headerName: "Descrizione",
    sortable: false,
    editable: true,
    width: 250,
  },
  {
    field: "dex2",
    headerName: "Descrizione Est.",
    sortable: false,
    editable: true,
    width: 200,
  },
  {
    field: "prezzo_un_lordo",
    cellClassName: "super-app-theme--green",
    headerName: "Prezzo un.",
    width: 120,
    editable: true,
    type: "number",
    sortable: false,
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
  },
  {
    field: "sconto_vend",
    editable: true,
    type: "number",
    headerName: "Sconto",
    align: "right",
    sortable: false,
    width: 80,
    valueFormatter: ({ value }) => (value ? value + "%" : "no"),
  },
  {
    field: "prezzo_un_netto",
    headerName: "Prez. netto un.",
    sortable: false,
    width: 130,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
  },
  {
    field: "um",
    headerName: "Um",
    sortable: false,
    align: "center",
    width: 60,
    cellClassName: "super-app-theme--centeredColumn",
  },
  {
    field: "qta",
    editable: true,
    type: "number",
    headerName: "Qta",
    align: "center",
    sortable: false,
    width: 60,
  },
  {
    field: "cod_iva",
    headerName: "IVA",
    align: "center",
    sortable: false,
    width: 60,
  },
  {
    field: "prz_tot_ivato",
    headerName: "Importo",
    sortable: false,
    width: 100,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
  },
];

export { odv_pro_id_details };
