const odv_pro_id_details = [
  {
    field: "marchio",
    headerName: "Marchio",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "linea",
    headerName: "Linea",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "codice",
    headerName: "Codice",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "dex",
    headerName: "Descrizione",
    sortable: false,
    editable: true,
    flex: 2.5,
  },
  {
    field: "dex2",
    headerName: "Descriz. estesa",
    sortable: false,
    editable: true,
    flex: 1.7,
  },
  {
    field: "prezzo_un_lordo",
    cellClassName: "super-app-theme--green",
    headerName: "Prezzo un.",
    editable: true,
    type: "number",
    sortable: false,
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
  {
    field: "sconto_vend",
    editable: true,
    type: "number",
    headerName: "Sconto",
    width: 70,
    align: "right",
    sortable: false,
    valueFormatter: ({ value, id, api }) => {
      let row = api.getRow(id);
      return value ? value + "%" : row?.netto_vend ? "Netto" : "";
    },
  },
  {
    field: "prezzo_un_netto",
    headerName: "Netto un.",
    sortable: false,
    editable: true,
    type: "number",
    width: 130,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value ? (value + " €").replace(".", ",") : ""),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
  {
    field: "um",
    headerName: "Um",
    sortable: false,
    width: 50,
    align: "center",
    cellClassName: "super-app-theme--centeredColumn",
  },
  {
    field: "qta",
    editable: true,
    type: "number",
    minWidth: 70,
    maxWidth: 80,
    headerName: "Qta",
    align: "right",
    sortable: false,
    flex: 0.2,
  },
  {
    field: "cod_iva",
    headerName: "IVA",
    width: 50,
    align: "center",
    sortable: false,
  },
  {
    field: "prz_tot_ivato",
    headerName: "Importo",
    sortable: false,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
];

const odv_pro_id_row_details = [
  {
    field: "marchio",
    headerName: "Marchio",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "linea",
    headerName: "Linea",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "codice",
    headerName: "Codice",
    sortable: false,
    editable: true,
    maxWidth: 220,
    flex: 1,
  },
  {
    field: "dex",
    headerName: "Descrizione",
    sortable: false,
    editable: true,
    flex: 2.5,
  },
  {
    field: "dex2",
    headerName: "Descriz. estesa",
    sortable: false,
    editable: true,
    flex: 1.7,
  },
  {
    field: "prezzo_un_lordo",
    cellClassName: "super-app-theme--green",
    headerName: "Prezzo un.",
    editable: true,
    type: "number",
    sortable: false,
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
  {
    field: "sconto_acquisto",
    editable: false,
    type: "number",
    headerName: "Sconto",
    width: 70,
    align: "right",
    sortable: false,
    valueFormatter: ({ value, id, api }) => {
      let row = api.getRow(id);
      return value ? value + "%" : row?.netto_vend ? "Netto" : "";
    },
  },
  {
    field: "costo_un_mio",
    headerName: "Netto un.",
    sortable: false,
    editable: false,
    type: "number",
    width: 130,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value ? (value + " €").replace(".", ",") : ""),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
  {
    field: "um",
    headerName: "Um",
    sortable: false,
    width: 50,
    align: "center",
    cellClassName: "super-app-theme--centeredColumn",
  },
  {
    field: "qta",
    editable: true,
    type: "number",
    minWidth: 70,
    maxWidth: 80,
    headerName: "Qta",
    align: "right",
    sortable: false,
    flex: 0.2,
  },
  {
    field: "cod_iva",
    headerName: "IVA",
    width: 50,
    align: "center",
    sortable: false,
  },
  {
    field: "total",
    headerName: "Tot. s/iva",
    sortable: false,
    cellClassName: "super-app-theme--green",
    align: "right",
    valueFormatter: ({ value }) => (value + " €").replace(".", ","),
    minWidth: 100,
    maxWidth: 120,
    flex: 0.5,
  },
];

export { odv_pro_id_details, odv_pro_id_row_details };
